name: try-bluetoothctl
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: dev
description: |
  dev

grade: stable
confinement: strict

apps:
  bluetoothctl:
    command: bin/bluetoothctl.sh

plugs:
  bluetoothctl:
    interface: content
    content: bluetoothctl
    target: $SNAP/bluetoothctl_dir
  bluetooth-control:
  bluez:

parts:
  launcher:
    plugin: dump
    source: launchers
